---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604

  - distro: debian9
    playbook: test-geoip.yml
  - distro: debian8
    playbook: test-geoip.yml
  - distro: ubuntu1804
    playbook: test-geoip.yml
  - distro: ubuntu1604
    playbook: test-geoip.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export DOCKER="docker exec --tty ${container_id} env TERM=xterm"

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure PHP is installed.
  - ${DOCKER} which nginx
  - ${DOCKER} nginx -v
  - ${DOCKER} test -x /usr/sbin/nginx
  - ${DOCKER} curl http://127.0.0.1/ | grep "Welcome to nginx"

  # Ensure nginx is started
  - ${DOCKER} systemctl --no-pager status nginx | grep 'nginx.service; enabled'
  - ${DOCKER} systemctl --no-pager status nginx | grep 'running'

  - |
    if [ "${playbook:-''}" == "test-geoip.yml" ]; then
      ${DOCKER} nginx -V 2>&1 | tr -- - '\n' | grep http_geoip_module
    fi


after_failure:
  - ${DOCKER} nginx -v
  - ${DOCKER} curl http://127.0.0.1/
  - ${DOCKER} service nginx status
  - ${DOCKER} ansible --version

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
