---
services: docker

env:
#  - distro: centos7
#  - distro: centos6
#  - distro: fedora27
#  - distro: ubuntu1604
#  - distro: ubuntu1404
#  - distro: ubuntu1204

  - distro: debian9
  - distro: debian8
  - distro: ubuntu1804
  - distro: ubuntu1604
  - distro: ubuntu1404

  - distro: debian9
    playbook: test-geoip.yml
  - distro: debian8
    playbook: test-geoip.yml
  - distro: ubuntu1804
    playbook: test-geoip.yml
  - distro: ubuntu1604
    playbook: test-geoip.yml
  - distro: ubuntu1404
    playbook: test-geoip.yml

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/tschifftner/4078cf2a8429d967d5e100649ff2caa9/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Ensure PHP is installed.
  - 'docker exec --tty ${container_id} env TERM=xterm which nginx'
  - 'docker exec --tty ${container_id} env TERM=xterm nginx -v'
  - 'docker exec --tty ${container_id} env TERM=xterm test -x /usr/sbin/nginx'
  - 'docker exec --tty ${container_id} env TERM=xterm curl http://127.0.0.1/ | grep "Welcome to nginx"'

  - |
    if [ "${playbook:-''}" == "test-geoip.yml" ]; then
      docker exec --tty ${container_id} env TERM=xterm nginx -V 2>&1 | tr -- - '\n' | grep http_geoip_module
    fi


after_failure:
  - docker exec --tty ${container_id} env TERM=xterm nginx -v
  - docker exec --tty ${container_id} env TERM=xterm curl http://127.0.0.1/
  - docker exec --tty ${container_id} env TERM=xterm service nginx status
  - docker exec --tty ${container_id} env TERM=xterm ansible --version

notifications:
  slack: ambimax:2MlPTX9bY9aPxCPhJGxHKIT6
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
