---

- name: Ensure directory exists
  file:
    path: '{{ nginx_dhparam_file | dirname }}'
    state: directory
    owner: root
    group: root
    mode: '0600'

- name: Generate dhparam file
  openssl_dhparam:
    path: '{{ nginx_dhparam_file }}'
    size: '{{ nginx_dhparam_size }}'
  notify: reload nginx
