---

- name: Ensure directory exists
  file:
    path: '{{ nginx_dhparam_file | dirname }}'
    state: directory
    owner: root
    group: root
    mode: '0600'

- openssl_dhparam:
    path: '{{ nginx_dhparam_file }}'
    notify: reload nginx
