---

- name: Install requirements first
  include: requirements.yml

- name: Use dotdeb only when Debian Jessie is installed
  set_fact:
    nginx_use_dotdeb: false
  when: ansible_distribution_release != 'jessie'

- name: Install with dotdeb
  include: install-dotdeb.yml
  when: nginx_use_dotdeb == true

- name: Install by default
  include: install-default.yml
  when: nginx_use_dotdeb == false
